# Setting to true disables the block damage for the selected entity.
# Setting to false causes the default behaviour, which destroys blocks.

ghast: True
creeper: True
wither: False 
enderdragon: False #Recommended if you're spawning one in the overworld.
tnt: False
tntcart: False
bed/other: False #Explosions from beds in the nether or end, as well as potentially other explosions that I've overlooked.

# Set this to false if you don't want the extra console output.
# This is potentially bad if used with Enderdragon or Wither set to true.

logging: True