name: '${project.name}'
main: com.kdude63.antisplosion.Main
version: '${project.version}'
description: Disables block damage from explosions throughout the server.
author: kdude63
dev-url: '${project.url}'
