name: AntiSplosion
main: com.kdude63.antisplosion.main
version: 1.1
description: Configurable to disable explosions and Enderdragon damage.
author: kdude63
dev-url: http://dev.bukkit.org/server-mods/antisplosion/
